theme = "onedark"

[editor]
scroll-lines = 4
shell = ["nu", "-c"]
cursorline = true
bufferline = "always"
text-width = 99
completion-timeout = 5
completion-trigger-len = 1
rulers = [100]

[editor.lsp]
display-inlay-hints = true

[editor.search]
smart-case = false

[editor.statusline]
left = ["mode"]
center = ["primary-selection-length"]
right = ["position"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
nbsp = "all"
nnbsp = "all"
tab = "all"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
